### PR TITLE
Change the Set method of Vector to SetVec. This enforces at compile t…

### PR DESCRIPTION
**Pull request by btracey**
…ime that the 'column' is zero

Fixes Issue 154.

### CODE REVIEW

**Comment by btracey** [comment]
Fixes issue #154

**Comment by btracey** [comment]
Good catch Travis.

**Comment by kortschak** [comment]
Make the index label i instead of r?

**Comment by btracey** [comment]
I almost changed it, but I thought this might help reinforce the idea that Vector is a column vector in other operations. Happy to go either way.

**Comment by kortschak** [comment]
OK

**Comment by btracey** [comment]
Is that the same as a LGTM?

**Comment by kortschak** [comment]
Sure.

**Comment by kortschak** [comment]
Sorry, I meant I accepted your explanation - leaving it as r is fine, but i is good too.

LGTM

**Comment by btracey** [comment]
Changed to i. You're right, it's better.

**Pull request merged**
