### PR TITLE
fix index out of range on lu decomp when m < n

### PR DESCRIPTION
**Pull request by rwcarlsen**
I'm not sure this is the fix you will want, but currently, LUGaussian panics when there are more columns than rows.  I haven't checked LU.

### CODE REVIEW

**Comment by rwcarlsen** [comment]
LU seems to work fine - just LUGaussian was broken.

**Comment by kortschak** [comment]
I vaguely recall we were planning to drop LUGaussian, but having it correct before putting it to sleep would be nice. Do you have any memory of that @btracey?

@rwcarlson, please revert the change to the test imports it is not necessary, I we're going to keep LUGaussian it would be good to add it to the tests though.

**Comment by kortschak** [comment]
... for this particular previously failing case.

**Comment by rwcarlsen** [comment]
sorry - goimports hook got me.  This also fixes the same problem on the type LU in general - calling the U() method when m < n also resulted in an index out of range panic.

**Comment by btracey** [comment]
I don't remember the previous conversation, but it seems like it should eventually go to sleep. Personally, I think a lot of these should be rethought with Lapack and SymDense etc. in mind. However, that requires time and effort, and so in the mean time the code should be correct. 

I agree that we should add tests. Thanks for the contribution @rwcarlsen

**Pull request closed without merging**
