### PR TITLE
Added SymRankOne method and tests to SymDense

### PR DESCRIPTION
**Pull request by btracey**

### CODE REVIEW

**Comment by btracey** [comment]
Will condense

**Comment by btracey** [comment]
@jonlawlor does coveralls consider it a failure if the test coverage decreased, or is it finding a different build failure than travis?

**Comment by kortschak** [comment]
LGTM

That's crazy, coverage changes within noise (if at all) should not be failures.

**Comment by jonlawlor** [comment]
@btracey, @kortschak, the coverage decrease failure appears to be a new "feature" enabled by default by coveralls.  I've since disabled it on all of the gonum repos.

**Comment by kortschak** [comment]
Thank you.

**Pull request merged**
