### PR TITLE
allow epsilon specification for the Factorize method, issue #313

### PR DESCRIPTION
**Pull request by idavydov**
Proposed a temporary fix.
It's good to have a control over epsilon, since it affects the eigen performance.

### CODE REVIEW

**Comment by kortschak** [comment]
I don't think we can have a method Factorize that takes an epsilon. We can provide a Factorize that hand over a reasonable epsilon (the lowest value that works for your failing case, multiplied by ~10 is probably reasonable). We could conceivable offer a temporary FactoriseEpsilon, thought I don't like that much.

**Comment by idavydov** [comment]
Can we have something like this?

    type Eigen struct {
            vectorsComputed bool
    
            n int // The size of the factorized matrix.
    
            ef eigenFactors
            
            Epsilon float64
    }

    func NewEigen() *Eigen {
        return &Eigen{Epsilon: 1e-9}
    }

**Comment by kortschak** [comment]
We can with similar qualms. The issue is that when the implementation is changed to be based on LAPACK, there is no such API. The exported Epsilon field would have to be marked as temporary. I'll leave it to @btracey to make this decision.

**Comment by btracey** [comment]
Does the epsilon change at which your code hangs? I'd rather just set epsilon to 1e-8 or thereabouts.

**Comment by btracey** [comment]
So you know @idavydov , part of the hesitancy to add the field is that I do not know when this code will get replaced with Dgeev. There are roughly 18 lapack functions that need to be implemented which is a lot of work.

**Comment by idavydov** [comment]
@btracey the minimal epsilon value at which it works is 1e-310, 1e-311 hangs (I suppose it's zero in float64 representation?).
I think something like 1e-8 is a reasonable default choice. But I have to note that eigen with epsilon 1e-9 is 100 time faster compared to epsilon=1e-310. That's why I think it might be useful to be able to tweak this.
At least for now, while it's not LAPACK. 
For my code something like 1e-8 should be a reasonable value.

**Comment by btracey** [comment]
Is 1e-9 100 times faster that 1e-16 (machine precision), or basically the same? 

We'd like API stability, and this function will lag that. When it eventually gets switched over, it would be nice to have similar (or faster) performance. The problem with an epsilon field is that not only will its removal break code, but it also allows users to run with a tolerance of 1e-1 or something to quickly get approximate eigenvalues. This is not possible to do with the Lapack implementation. In short, the tolerance field could break both compiling, but also break algorithms. If something like 1e-8 or 1e-16 performs reasonably, then it seems closer to what the eventual behavior will be, thus increasing stability.

**Comment by idavydov** [comment]
@btracey 1e-16 is ~20% slower compared to 1e-9. I think that should be ok for the most applications.

**Comment by btracey** [comment]
1e-16 sounds good to me.

**Pull request closed without merging**
