### PR TITLE
fix issue #313 by increasing epsilon

### PR DESCRIPTION
**Pull request by idavydov**
In some cases eigen hangs.
https://gist.github.com/idavydov/eb4c88b4663a7240c92f
It works ok with epsilon=1e-15 works, 1e-14 to be safe, as this code is going to be replaced in future.

### CODE REVIEW

**Comment by btracey** [comment]
Lgtm. If only dgeev wasn't so much work...

**Comment by btracey** [comment]
Look good to you as well @kortschak ?

**Comment by kortschak** [comment]
Yes, there was not problem here for me, I just like to leave the finer points of numerical things to you since you have very much more experience.

LGTM

**Pull request merged**
