### PR TITLE
Update travis to test matrix with different build tag options.

### PR DESCRIPTION
**Pull request by btracey**
Especially with our use of assembly, we should check that the tests pass under a variety of conditions

### CODE REVIEW

**Comment by btracey** [comment]
This should fail now because of #142 .

**Comment by kortschak** [comment]
Passes.

**Comment by btracey** [comment]
Why does it pass? I'm pretty sure the Inner code is incorrect, as is evidenced by the out-of-bounds error on my machine. 

Here is my output
````
brendan:~/Documents/mygo/src/github.com/gonum/matrix/mat64$ git branch
  fixcholcheck
  fixinner
  lapackchol
* master
  pool
  updatetravis
  vecsolvechol
brendan:~/Documents/mygo/src/github.com/gonum/matrix/mat64$ git pull
Already up-to-date.
brendan:~/Documents/mygo/src/github.com/gonum/matrix/mat64$ go test -tags noasm

----------------------------------------------------------------------
PANIC: inner_test.go:89: S.TestInnerSym

... Panic: runtime error: index out of range (PC=0x3BB55)

/Users/brendan/gover/go/src/runtime/panic.go:387
  in gopanic
/Users/brendan/gover/go/src/runtime/panic.go:12
  in panicindex
/Users/brendan/Documents/mygo/src/github.com/gonum/internal/asm/ddot.go:18
  in DdotInc
inner.go:53
  in Inner
inner_test.go:120
  in S.TestInnerSym
/Users/brendan/gover/go/src/reflect/value.go:296
  in Value.Call
/Users/brendan/gover/go/src/runtime/asm_amd64.s:2232
  in goexit
OOPS: 54 passed, 1 PANICKED
--- FAIL: Test (0.83s)
FAIL
exit status 1
FAIL	github.com/gonum/matrix/mat64	0.837s
````

**Comment by kortschak** [comment]
Crazy. This panics for me now, though didn't five minutes ago.

```
$ go test -tags noasm
OK: 55 passed
PASS
ok  	github.com/gonum/matrix/mat64	1.988s
$ go test -tags noasm
----------------------------------------------------------------------
PANIC: inner_test.go:89: S.TestInnerSym

... Panic: runtime error: index out of range (PC=0x43A955)

/home/daniel/Development/go/src/runtime/panic.go:387
  in gopanic
/home/daniel/Development/go/src/runtime/panic.go:12
  in panicindex
/home/daniel/Development/src/github.com/gonum/internal/asm/ddot.go:18
  in DdotInc
inner.go:53
  in Inner
inner_test.go:120
  in S.TestInnerSym
/home/daniel/Development/go/src/reflect/value.go:296
  in Value.Call
/home/daniel/Development/go/src/runtime/asm_amd64.s:2232
  in goexit
OOPS: 54 passed, 1 PANICKED
--- FAIL: Test (2.07s)
FAIL
exit status 1
FAIL	github.com/gonum/matrix/mat64	2.080s
```

**Comment by btracey** [comment]
Huh. That's not encouraging. Is it consistently failing now?

**Comment by kortschak** [comment]
Yes. I have no idea why. Now we wait for travis to do something for us - it has been horrible for the past couple of days.

**Comment by btracey** [comment]
It shows passing for me. It doesn't for you? I'm more nervous that the
other PR passes with the noasm build tag

**Comment by kortschak** [comment]
github has not updated. At travis, it's waiting to start.

**Comment by vladimir-ch** [comment]
The same situation for me: at first it consistently passed, then I added a print statement to asm/ddot.go and since then it consistently fails (with or without printing).

**Comment by kortschak** [comment]
See if we can get back to the passing case by blowing away $GOPATH/pkg/. I think this is likely to be a compiler bug.

**Comment by kortschak** [comment]
Nope.

**Comment by vladimir-ch** [comment]
I can get it to the passing state: `go install` in asm.

I am on linux.

**Comment by kortschak** [comment]
That works for me. Good.

**Comment by kortschak** [comment]
`go test -gcflags='-N' -tags noasm` doesn't fail either, so it's not in-lining.

**Comment by kortschak** [comment]
LGTM

**Comment by kortschak** [comment]
The ordering of these merges (wrt #142) is unfortunate for dealing with the possible compiler bug.

**Comment by btracey** [comment]
You're right. I should have thought about that. Sorry.

**Comment by kortschak** [comment]
No worries, easily fixed.

**Pull request merged**
