### PR TITLE
Add tolerance for testtwoinput equality

### PR DESCRIPTION
**Pull request by btracey**

### CODE REVIEW

**Comment by btracey** [comment]
Fixes #234

**Comment by btracey** [comment]
If you'd like I can delete equalApprox and use EqualApprox in this PR.

**Comment by kortschak** [comment]
I was thinking of doing that previously, but we don't test EqualApprox AFAIR.

LGTM

**Comment by kortschak** [comment]
This is #234. I don't understand the fixes comment.

**Comment by btracey** [comment]
Sorry, I meant #232 

http://godoc.org/github.com/gonum/matrix/mat64#EqualApprox ?

**Comment by kortschak** [comment]
No, I mean that when I was looking to delete equalApprox in the testing code it looked to me that it is a simpler algorithm (it does no type-dependent tricks), so it should be left.

**Comment by btracey** [comment]
Ah, I see. Great.

**Pull request merged**
