### PR TITLE
Convenience functions (+update of the check package to github)

### PR DESCRIPTION
**Pull request by antoine-lizee**
Few Convenience functions for Matrix manipulation + their tests.
I have not changed the API (yet?).

I also updated the check package, that has migrated to github.

### CODE REVIEW

**Comment by kortschak** [comment]
I would really like these doc comments to go in, but the PR no longer merges. I'm going to close. If you would like to send a new PR with the documentation only, that would be greatly appreciated.

**Comment by lazywei** [comment]
@antoine-lizee I'll try to include the docs you wrote in my PR #105, all credits go to you of course, please let me know if you're not comfortable with that. Thanks.

**Comment by antoine-lizee** [comment]
Please go-ahead! Thanks for the good etiquette.

**Comment by kortschak** [comment]
Thanks, Antoine.

**Pull request closed without merging**
