### PR TITLE
mat64: update outer product methods

### PR DESCRIPTION
**Pull request by kortschak**
@btracey

### CODE REVIEW

**Comment by btracey** [comment]
Referencing an offline discussion:

I think there is merit to having both outer and RankOne. Outer stores a new result, while RankOne updates a matrix. Even when RankOne is changed to not allocate, Outer could still be used to generate the original matrix (starting from a zero matrix), while RankOne has to have a non-zero matrix argument. 

I think cross-comments between the methods are useful.

**Comment by btracey** [comment]
LGTM

**Comment by kortschak** [comment]
Would you like these added? I'm not sure I understand.

**Comment by btracey** [comment]
Off of list, you said 

" If we do that, we should add a sentence to the docs saying RankOne is the equivalent to outer explcitly, numpy e.g. calls it outer - so it would be easier for people to find if it at least mentioned that name."

I see that I misread it, and you meant if we didn't have Outer. I do think that it would be useful to have on the Outer method 
````
In order to update to an existing matrix, see RankOne
````
and for RankOne
````
If a is zero, see Outer.
````

**Comment by kortschak** [comment]
I'll add those.

**Pull request merged**
