### PR TITLE
Minor cleanup in mat64

### PR DESCRIPTION
**Pull request by vladimir-ch**

### CODE REVIEW

**Comment by btracey** [comment]
LGTM

**Comment by kortschak** [comment]
Would you rename rowView to rawRowView while you're here?

**Comment by btracey** [comment]
Good idea

**Comment by kortschak** [comment]
LGTM after that.

I think there is an opportunity to put bounds checks in rawRowView (in two versions - check and nocheck) for column width. This goes part of the way towards my slice bounds checking issue. The use of rawRowView can then be extended in use.

**Pull request merged**
