### PR TITLE
Make use of gonum/blas/blas64

### PR DESCRIPTION
**Pull request by kortschak**
This is part of a set of changes to rationalise and centralise BLAS implementation registration.

It is expected to fail until gonum/blas#83 has been merged. Review that PR first.

### CODE REVIEW

**Comment by jonlawlor** [comment]
There are [60 downstream packages](http://godoc.org/github.com/gonum/matrix/mat64?importers) (!) that will be broken by this change:
* many are subpackages or forks of [golearn](http://godoc.org/github.com/sjwhitworth/golearn)
* [go-nets](https://github.com/antoine-lizee/go-nets/blob/master/network.go#L21) also uses it
* some are gonum (specifically, optimize.  stat uses it but looks ok)
* some are owned by @btracey

**Comment by kortschak** [comment]
The only change required in those packages will be the deletion of the `mat64.Register()` call unless people are doing `RawMatrix` matrix construction (`RawMatrix()` calls will continue to work as previously unless people predeclare their vars). Also the changes at gonum/blas#83 already will have broken those packages.

The pain will be worthwhile in the long term.

**Comment by btracey** [comment]
Nothing exported depends on BLAS except the call to Register. Register going away will break stuff, but the fix is either a deletion (if you were using goblas) or a one line fix (from cblas.Blas{} to cgo.Implementation{}). The removal of RawMatrix is potentially more damaging, but at least the types are identical. If you were using RawMatrix() and :=, possibly nothing will need to change. Otherwise, some names will need to change. This is unfortunate, but we're still too young an ecosystem to be unable to make breaking changes. This set of changes is how the blas organization should be, and hopefully we won't have to break this again.

**Comment by btracey** [comment]
@sjwhitworth, @antoine-lizee, @dane-unltd, @jesand, @kse we're sorry for the break, but it's for the best long-term

**Comment by jonlawlor** [comment]
I'll put together a notification for them tomorrow.

**Comment by btracey** [comment]
LGTM. I just looked at the diff, so there may be unchanged comments, but if they got through comments are easy to fix.

**Comment by btracey** [comment]
Okay, now we see how badly all of my code breaks ...

**Pull request merged**
