### PR TITLE
mat64: add slicing bounds checks to Dense

### PR DESCRIPTION
**Pull request by kortschak**
This is a sketch for how we might do slicing bounds checks. At this stage for discussion.

Updates #150.

@btracey Please take a look.

### CODE REVIEW

**Comment by btracey** [comment]
I like the idea. Do we think it would be useful to also have helper routines "sliceRow, sliceRowTri" and the like? It may help write less buggy code.

**Comment by kortschak** [comment]
The intention was to have it for all, yes.

**Comment by btracey** [comment]
Sorry, we may have communicated properly, but I'm going to restate what we said in case we did not.

I like the code that exists there, but I'm suggesting in addition we may want to have helper scripts. The one there now is for getting a general subset of a row. We could also provide 
````
sliceDenseRow(m blas64.General, i) []float64{
     return m.Data[i*m.Stride: i*m.Stride + m.Cols]
}
````
which helps some common cases.

**Comment by kortschak** [comment]
Ahh, I missed that. Sure.

**Comment by kortschak** [comment]
Closing due to staleness. Will send another in due course.

**Pull request closed without merging**
